import prisma from "@/prisma/client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import AllProviders from "./AllProviders";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import "./globals.css";
import getSession from "./libs/getSession";

const iranYekan_bold = localFont({
  src: "./fonts/IRANYekanBold.ttf",
  variable: "--font-iran-yekan-bold",
});
const iranYekan_regular = localFont({
  src: "./fonts/IRANYekanRegular.ttf",
  variable: "--font-iran-yekan-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  const [notifications, unReadNotificationCount, authenticatedUser] =
    await Promise.all([
      prisma.notification.findMany({
        where: {
          isRead: false,
          assignedToUserId:
            session?.user.role === "USER" ? session?.user.id : undefined,
        },

        orderBy: { createdAt: "desc" },
        take: 5,
      }),

      prisma.notification.count({
        where: {
          isRead: false,
          assignedToUserId:
            session?.user.role === "ADMIN" ? undefined : session?.user.id,
        },
      }),

      session?.user
        ? prisma.user.findUnique({ where: { id: session?.user.id } })
        : undefined,
    ]);

  return (
    <html lang="fa" dir="rtl" className="bg-neutral-50">
      <body
        className={`${iranYekan_bold.variable} ${iranYekan_regular.variable} antialiased relative `}
      >
        <AllProviders>
          <div>
            <Sidebar session={session!} />
          </div>

          <main className={`flex flex-col ${session && "mr-[66px]"} h-full`}>
            <nav className="w-full">
              <Navbar
                session={session!}
                authenticatedUser={authenticatedUser!}
                unReadNotificationCount={unReadNotificationCount}
                notifications={notifications}
              />
            </nav>

            {children}
          </main>
        </AllProviders>
      </body>
    </html>
  );
}
