import type { Metadata } from "next";
import localFont from "next/font/local";
import AllProviders from "./AllProviders";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import "./globals.css";

const iranYekan_bold = localFont({
  src: "./fonts/IRANYekanBold.ttf",
  variable: "--font-iran-yekan-bold",
});
const iranYekan_regular = localFont({
  src: "./fonts/IRANYekanRegular.ttf",
  variable: "--font-iran-yekan-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${iranYekan_bold.variable} ${iranYekan_regular.variable} antialiased relative h-screen bg-neutral-100`}
      >
        <AllProviders>
          <div>
            <Sidebar />
          </div>

          <main className="flex flex-col mr-[66px] h-full ">
            <nav className="w-full">
              <Navbar />
            </nav>

            {children}
          </main>
        </AllProviders>
      </body>
    </html>
  );
}
